[project]
name = "agents-for-2048"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "2048-pyo3",
    "gymnasium>=1.2.2",
    "torch>=2.9.0",
]

[tool.uv.sources]
2048-pyo3 = { path = "submodules/2048.pyo3" }
