[observation_space]
low = 0
high = 65536
shape = [4, 4]

[action_space]
num_actions = 4

[rendering]
mode = "non-human"
number_of_tiles = 4  # What does size do in my environment?
tile_size = 100
gap_between_tiles = 10
margin_size = 20
background_color = [ 255, 251, 240 ]
empty_tile_color = [ 205, 192, 180 ]
font_color = [ 0, 0, 0 ]
font_size = 40
font = "arial"
fps = 4

[rendering.tile_colors]
"2" = [ 238, 228, 218 ]
"4" = [ 237, 224, 200 ]
"8" = [ 242, 177, 121 ]
"16" = [ 245, 149, 99 ]
"32" = [ 246, 124, 95 ]
"64" = [ 246, 94, 59 ]
"128" = [ 237, 207, 114 ]
"256" = [ 237, 204, 97 ]
"512" = [ 237, 200, 80 ]
"1024" = [ 237, 197, 63 ]
"2048" = [ 237, 194, 46 ]
